codebreaker gem
BogdanPerekhrest34/codebreaker pull request #1
Opened 2022-02-11 17:20 UTC by BogdanPerekhrest34

done codebreaker gem by https://docs.google.com/document/d/1VW3Mk1WpGkq0FadPih689_k971Zy8inzk6UCPHDLzs/view#

2022-02-14 15:06 UTC, nico-saj requested changes

2022-02-14 15:06 UTC, nico-saj commented on spec/codebreaker_gem/codebreaker_spec.rb
> +RSpec.describe Codebreaker::Game do
U have to add tests for all examples from 'Codebreaker Examples Matrix'

2022-02-15 10:38 UTC, nico-saj requested changes

2022-02-19 12:34 UTC, nico-saj requested changes
Recheck logic and fix it. I can't check further PRs while ur game has incorrect logic!

2022-02-19 12:34 UTC, nico-saj commented on lib/codebreaker/game.rb
> +  DIFFICULTY = {
Don't set constants out of class. Move them to Game class

2022-02-19 12:34 UTC, nico-saj commented on spec/codebreaker_gem/codebreaker_spec.rb
> +      ['6543', '6666', %w[+ - - -]]
If secret code = 6543 and user code = 6666, response have to be '+'. U can find it in `Codebreaker Examples Matrix`

2022-02-22 13:49 UTC, nico-saj requested changes

2022-02-22 13:49 UTC, nico-saj commented on spec/codebreaker_gem/codebreaker_spec.rb
> +      ['6543', '5643', %w[- - + +]], ['6543', '6411', ['+', '-', ' ', ' ']],
`['6543', '5643', %w[+ + - -]]` and `['6543', '6411', %w[+ -]]` 
Also use the same style and remove empty strings.

2022-02-22 18:59 UTC, nico-saj requested changes

2022-02-22 18:59 UTC, nico-saj commented on lib/codebreaker/save_result_module.rb
> +module SaveResultModule
U can't save score in gem and load it in console. All these logic have to be in gem.

2022-02-22 18:59 UTC, nico-saj commented on lib/codebreaker/game.rb
> +        next if @output_number[index] == '+'
Why do u need this?

2022-02-22 18:59 UTC, nico-saj commented on spec/codebreaker_gem/codebreaker_spec.rb
> +      ['6543', '2666', %w[-]]
Add one more case: ['1234', '4444', %w[+]]

2022-02-24 11:17 UTC, BogdanPerekhrest34 commented on lib/codebreaker/game.rb
> +        next if @output_number[index] == '+'
what exactly?

2022-03-07 09:54 UTC, nico-saj approved these changes

2022-03-07 09:54 UTC, nico-saj commented on lib/codebreaker/save_result_module.rb
> +module SaveResultModule
U forgot about `module Codebreaker`

2022-03-07 09:54 UTC, nico-saj commented on lib/codebreaker/save_result_module.rb
> +    full_path_file = "#{full_path}/score.yml"
Move filename to constant

2022-03-07 09:54 UTC, nico-saj commented on lib/codebreaker/loader_module.rb
> +      full_path ||= File.expand_path('./data/score.yml', __dir__)
Move filename to constant

2022-03-07 10:03 UTC, merged